services:
  - type: web
    name: obs-webhook-bridge
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python obs_webhook_bridge.py
    envVars:
      - key: OBS_HOST
        value: localhost
      - key: OBS_PORT
        value: 4460
      - key: BROWSER_SOURCE_NAME
        value: FOSTER NINJA
      - key: EXPECTED_API_KEY
        value: cnl3_secret_2025
