services:
  - type: web
    name: obs-webhook-bridge
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python obs_webhook_bridge.py
    envVars:
      - key: OBS_HOST
        fromEnv: OBS_HOST
      - key: OBS_PORT
        fromEnv: OBS_PORT
      - key: BROWSER_SOURCE_NAME
        fromEnv: BROWSER_SOURCE_NAME
      - key: EXPECTED_API_KEY
        fromEnv: EXPECTED_API_KEY
